{% set version = "3.2.0" %}

package:
  name: sgpp
  version: {{ version }}

source:
  fn: sgpp-{{ version }}.tar.gz
  url: https://github.com/SGpp/SGpp/archive/v{{ version }}.tar.gz
  sha256: dab83587fd447f92ed8546eacaac6b8cbe65b8db5e860218c0fa2e42f776962d
  patches:
    - osx.patch

build:
  number: 0
  skip: true  # [win or not py3k]

requirements:
  build:
    - swig
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - scons
    - setuptools
    - python
    - numpy
    - llvm-openmp  # [osx]
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - llvm-openmp  # [osx]

test:
  imports:
    - pysgpp

about:
  home: http://sgpp.sparsegrids.org/
  license: BSD 3-Clause
  license_file: LICENSE.md
  summary: A numerical library for adaptive Sparse Grids

extra:
  recipe-maintainers:
    - jschueller
